### ISSUE TITLE
db.instance tag for elasticsearch to enable as inferred service

### ISSUE THREAD

**Issue by hackerrdave** [signalfx/signalfx-python-tracing#33]
The elasticsearch tracing library doesn't add the span tag `db.instance`, so elasticsearch is never picked up as an inferred service in the service map. Is there a plan to add this?

Thanks!

**Comment by rmfitzpatrick** [comment]
@hackerrdave thanks for opening this.  We do plan on adding this to the [Elasticsearch instrumentation](https://github.com/opentracing-contrib/python-elasticsearch/).  This would be part of a larger planned audit for inferred service compatibility and upstream instrumentations in the near future.

Depending on your use case, we think that the cluster name would be the preferred `db.instance` value as there could be some cardinality concerns with using index names.  Perhaps being able to configure which to use would be ideal.

In the meantime there isn't  span tags parameter like with some other instrumentations, so no immediate workaround seems available.  Of course opening a PR for the instrumentation is always an option if your schedule allows it 😄

**Comment by hackerrdave** [comment]
great thanks for the update! Agreed on the `db.instance` value being the cluster name rather than the index names. I may be able to try to work this in, just wanted to confirm that this is something that we wanted to do, and wasn't already being worked on. It does seem to be a bit of a larger refactor than the other recent changes to pymysql since that integration was already refactored in a way to have access to span tags, but I'll see what I can do!
